### ISSUE TITLE
Feature Question

### ISSUE THREAD

**Issue by darkogav** [nickcernis/studiopress-cli#5]
Hi Nick, is it possible to integrate this onto the wp-cli install on the system so it works for all WordPress sites on the system or do we have to keep installing it individually on each WP install that uses Genesis?

**Comment by nickcernis** [comment]
My plan is to eventually release it as a [WP CLI package](http://wp-cli.org/package-index/) so that you could install it globally: https://github.com/nickcernis/studiopress-cli/issues/3

Before that can happen I need to:
- Fix https://github.com/nickcernis/studiopress-cli/issues/1
- Write unit tests.

Thanks for your interest, though! Knowing others are checking in gives some extra motivation to finish this. Further thoughts and feedback is always welcome.
